# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- azp

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js 12.x'

- script: |
    npm install
    node --experimental-modules .azp/gen-all-deps.js
  displayName: 'Generate all deps files'

- bash: az storage blob upload-batch -d '$web/dtmi' --account-name iotmodelsregistry -s dtmi --if-unmodified-since 2018-01-01T01:01:01Z --account-key $KEY
  displayName: Copy Models and Deps to Storage iotmodelsregistry
  env:
    KEY: $(ACCESS_KEY)
