# This is a basic workflow to help you get started with Actions

name: validate-models

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v2
     
      - id: files
        uses: jitterbit/get-changed-files@v1
      
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: Add private feed
        run: |
         dotnet nuget add source https://nuget.pkg.github.com/iotmodels/index.json -n GPR -u ridomin -p ${{ secrets.GHPackagesToken }} --store-password-in-clear-text
         dotnet tool install --global dtdl2-validator --add-source https://nuget.pkg.github.com/iotmodels/index.json
      
      - name: Validate models edits
        run: .github/workflows/validate-models.sh ${{steps.files.outputs.added_modified}}
