name: validate-models

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
     
      - id: files
        uses: jitterbit/get-changed-files@v1

      - name: restore npm packages
        run: npm i
        
      - name: Validate Unique IDs
        run: node --experimental-modules .github/workflows/validate-ids.js ${{steps.files.outputs.added_modified}}
      
      - name: Install dtdl2-validator from GPR
        run: |
         dotnet nuget add source https://nuget.pkg.github.com/iotmodels/index.json -n GPR -u ridomin -p ${{ secrets.GHPackagesToken }} --store-password-in-clear-text
         dotnet tool install --global dtdl2-validator --add-source https://nuget.pkg.github.com/iotmodels/index.json
      
      - name: Parse models with local resolver
        run: .github/workflows/validate-models.sh ${{steps.files.outputs.added_modified}}

 
